apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: androidjobs.android.stf.io
spec:
  group: android.stf.io
  names:
    kind: AndroidJob
    listKind: AndroidJobList
    plural: androidjobs
    singular: androidjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AndroidJob is the Schema for the androidjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AndroidJobSpec defines the desired state of AndroidJob
          properties:
            deviceName:
              type: string
            deviceSelector:
              additionalProperties:
                type: string
              type: object
            jobTemplate:
              type: string
            ttlSecondsAfterCreation:
              type: integer
          required:
          - jobTemplate
          type: object
        status:
          description: AndroidJobStatus defines the observed state of AndroidJob
          properties:
            jobStatus:
              additionalProperties:
                description: DeviceJobStatus defines the state of the job for a single
                  device
                properties:
                  jobStatus:
                    description: Status is the current status of the job
                    type: string
                  message:
                    description: Message may contain extra information about the status
                      of the job
                    type: string
                type: object
              description: JobStatus is a map of device name to device status
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
