apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: androidjobtemplates.android.stf.io
spec:
  group: android.stf.io
  names:
    kind: AndroidJobTemplate
    listKind: AndroidJobTemplateList
    plural: androidjobtemplates
    singular: androidjobtemplate
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AndroidJobTemplate is the Schema for the androidjobtemplates API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AndroidJobTemplateSpec defines the desired state of AndroidJobTemplate
          properties:
            actions:
              items:
                properties:
                  activity:
                    type: string
                  apkURL:
                    type: string
                  commands:
                    items:
                      type: string
                    type: array
                  interactions:
                    items:
                      properties:
                        input:
                          type: string
                        target:
                          type: string
                        type:
                          type: string
                      type: object
                    type: array
                  name:
                    type: string
                  runAsRoot:
                    type: boolean
                  seconds:
                    type: integer
                required:
                - activity
                type: object
              type: array
          required:
          - actions
          type: object
        status:
          description: AndroidJobTemplateStatus defines the observed state of AndroidJobTemplate
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
